### ISSUE TITLE
issue with stage mag

### ISSUE THREAD

**Issue by svalenti** [LCOGT/lcogtsnpipe#66]
Depending if we run the mag stage on the full list of images or a single images 
lscloop.py -e 20190102-20190605 -n SN2018cuf --show -s mag --difftype 0 --filetype 3 --type ph -f apass -F

"cpt1m013-fa14-20190603-0233-e91.fa.diff.fits", 14, 20.621332, 0.315108547495),
("cpt1m013-fa14-20190603-0234-e91.fa.diff.fits", 14, 19.819498, 0.406084223658)

lscloop.py -e 20190602-20190605 -n SN2018cuf --show -s mag --difftype 0 --filetype 3 --type ph -f r -F

INSERT INTO photlco (filename, targetid, mag, dmag) VALUES
("cpt1m013-fa14-20190603-0233-e91.fa.diff.fits", 14, 9999.0, 9999.0),
("cpt1m013-fa14-20190603-0234-e91.fa.diff.fits", 14, 9999.0, 9999.0)

it seems is getting a color term from an observations months before

**Comment by griffin-h** [comment]
I think this is not because of the dates, but because of the filters you are choosing. In the first command you use `-f apass` and in the second command you use `-f r`. Since the zero point was calculated using the g-r color term (`ZPRGR` in the header), it cannot calculate the mag if you choose only one filter. I recommend you do not give the `-f` option for the mag stage (maybe we should add this to the instructions).

Try the second command again using `-f apass` and I think it should give the same result as the first command. I can't test this on the supernova machine because I haven't run the image subtraction there.

**Comment by griffin-h** [comment]
This is the same problem as Issue #23

**Comment by abostroem** [comment]
I updated the manual to warn against this option and explain it. I'm going to close this issue
