### ISSUE TITLE
matplotlib showing inaccurate psf in checkpsf stage with --no_iraf flag

### ISSUE THREAD

**Issue by navii98** [LCOGT/lcogtsnpipe#95]
Hi, I was working with assan14il data and while I was generating the PSFs for some particular epochs, I came across this issue.
Basically what is happening is the `-s checkpsf` and `-s checkpsf --no_iraf` commands are showing completely different images.

When I run -
```
supernova@a4bd83f4f33f:~$ lscloop.py -n asassn14il -e 20151026 -d 121 -s checkpsf
```
I get -
![image](https://user-images.githubusercontent.com/97835976/150012106-26ed6dbb-cc35-415d-b510-e8236f67fb60.png)

But when I run -
```
supernova@a4bd83f4f33f:~$ lscloop.py -n asassn14il -e 20151026 -d 121 -s checkpsf --no_iraf
```
I get - 
![image](https://user-images.githubusercontent.com/97835976/150012347-a59a4efc-fa01-47a4-b400-5d45fb76ba06.png)

which is something completely different and not even an psf.

The image itself looks pretty normal - 
![image](https://user-images.githubusercontent.com/97835976/150013170-20c5eca5-9bad-48c9-a82e-9a118e9fdc62.png)

This issue also happens with -d 122, 123, 124, 130 from the same -e 20151026. And with one or two images from other epochs as well, which I haven't written down.

**Comment by jfrostburke** [comment]
Thanks for noticing this and for opening an issue! Issue (mostly) fixed in PR #96.

The PSF in the iraf display is definitely the “right” PSF – the image looks normal but if you zoom in you can clearly see the sources are donuts (image attached).

<img width="500" alt="Screen Shot 2022-01-24 at 12 00 31 PM" src="https://user-images.githubusercontent.com/39279101/150855671-c018aca9-8309-4339-8d77-a7067e62fbae.png">

PSFs are saved in iraf as a combination of an analytical function (an elliptical Gaussian) and residuals. Since this PSF is very non-Gaussian, the residual component dominates. I had been combining the two components with the wrong normalization.

I looked around the iraf code for the right normalization and couldn’t actually find where it is defined. After testing a few things I got something that is close to right, but not exactly right, as you can see in the following image. This is the closest I could get, so I used that and added a printed warning for very non-Gaussian PSFs that `–no-iraf` might be displaying them incorrectly.

<img width="550" alt="Screen Shot 2022-01-24 at 12 00 48 PM" src="https://user-images.githubusercontent.com/39279101/150855663-2acf7c03-78dd-446a-9cc8-32d8b49df768.png">

**Comment by navii98** [comment]
I've noticed cases where iraf shows a very good psf model but matplotlib shows a barely usable one. I think the core issue is the same as you pointed out, this image is just an extreme example of it.

Btw, I made the same commits as PR #96 to my local `..../lcogtsnpipe/trunk/src/lsc/myloopdef.py` file and restarted the docker container to see the changes but I'm getting the same result. Do I have to do anything else with docker in order to implement the changes?

**Comment by navii98** [comment]
Okay, I had to build docker again as well. 
I just wanted to add that this commit also fixes the other discrepancies between matplotlib and iraf display as well. For example in the following image now matplotlib more faithfully represents what iraf shows.

Iraf display - 
![Screenshot from 2022-01-27 18-59-17](https://user-images.githubusercontent.com/97835976/151369495-b0804993-9806-428e-9f18-642b9674f64f.png)

old matplotlib image - 
![Screenshot from 2022-01-27 18-58-56](https://user-images.githubusercontent.com/97835976/151369803-88889362-c0cc-4c7d-a54c-dc8fcbec0896.png)

new matplolib image - 
![Screenshot from 2022-01-27 19-01-37](https://user-images.githubusercontent.com/97835976/151369873-e1479e9e-aa1e-44ea-b99f-85597cc1a2a9.png)
